server:
  servlet:
    context-path: /cinemas
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/hdqcinema?options=-c%20TimeZone=Asia/Ho_Chi_Minh" #?options=-c%20TimeZone=Asia/Ho_Chi_Minh
    password: 12345678
    username: my_app_user


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#      default_schema: public
#      jdbc.time_zone: "Asia/Ho_Chi_Minh"