version: "3.9"

services:
  frontend:
    build: .
    container_name: my-react-frontend-cinema
    restart: no
    ports:
      - "3000:80"
    expose:
      - "80"          # kh√¥ng publish ra host
    networks:
      - cinema-network

networks:
  cinema-network:
    external: true
